const SicboOperations = {
  ODD: 'SICBO_ODD',
  EVEN: 'SICBO_EVEN',
  BIG: 'SICBO_BIG',
  SMALL: 'SICBO_SMALL',
  DOUBLE_ONE: 'SICBO_DOUBLE_1_1',
  DOUBLE_TWO: 'SICBO_DOUBLE_2_2',
  DOUBLE_THREE: 'SICBO_DOUBLE_3_3',
  DOUBLE_FOUR: 'SICBO_DOUBLE_4_4',
  DOUBLE_FIVE: 'SICBO_DOUBLE_5_5',
  DOUBLE_SIX: 'SICBO_DOUBLE_6_6',
  TRIPLE_ONE: 'SICBO_SPECIFIC-TRIPLE_1_1_1',
  TRIPLE_TWO: 'SICBO_SPECIFIC-TRIPLE_2_2_2',
  TRIPLE_THREE: 'SICBO_SPECIFIC-TRIPLE_3_3_3',
  TRIPLE_FOUR: 'SICBO_SPECIFIC-TRIPLE_4_4_4',
  TRIPLE_FIVE: 'SICBO_SPECIFIC-TRIPLE_5_5_5',
  TRIPLE_SIX: 'SICBO_SPECIFIC-TRIPLE_6_6_6',
  TRIPLE_ANY: 'SICBO_TRIPLE',
  THREE_DICE_SUM: 'SICBO_SUM',
  DOUBLE_DICE_COMBINATION: 'SICBO_DICE-COMBO',
  SINGLE_DICE: 'SICBO_SINGLE-DICE',
  SICBO_SPECIFIC_TRIPLE: 'SICBO_SPECIFIC-TRIPLE',
  SICBO_DOUBLE: 'SICBO_DOUBLE'
}

export default SicboOperations
